### ISSUE TITLE
BlazorMobile.Build.Android tool fail on Android project build

### ISSUE THREAD

**Issue by OliverVisual** [Daddoon/BlazorMobile#133]
Updated to the latest version and seem to always hit this problem? 

5>------ Rebuild All started: Project: vamobile.Android, Configuration: Debug Any CPU ------
5>  Unhandled exception. Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument 
5>  'Visual\.nuget\packages\blazormobile.build.android\3.0.11-preview9.19465.2\tools\netcoreapp3.0/'
5>     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command
5>  , String[] args, Int32 index, String argTypeName)
5>     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
5>     at BlazorMobile.Build.Program.Main(String[] args) in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.Build.Android\C
5>  li\Program.cs:line 25

**Comment by Daddoon** [comment]
Can you send a repro project ? Thanks !

**Comment by Daddoon** [comment]
It’s surely about the Android CLI but i need to know what make it fail

**Comment by Daddoon** [comment]
- What is your Visual Studio version ?
- Do you have .NET Core 3.0 installed ? I forgot to write this as a requirement for the additionals CLI tools
- What is the folder structure of your project on your Filesystem ?

It seem that the error is when parsing the required arguments with the CLI.

According to the error, it seem to fail when arriving on the --package-dir option, see:

```xml
  <Target Name="_InjectBlazorMobileIFrameListenerWebExtension" BeforeTargets="CoreCompile">
    <Exec Command="$(BlazorMobileBuildAndroidFileExe) inject-iframe-listener-webextension --input $(BlazorMobileBuildAndroidInput) --package-dir $(BlazorMobileBuildAndroidDir) --intermediate-output-path $(BlazorMobileBuildAndroidIntermediateOutputPath)" />
  </Target>
```

This is the Android build target file.

You may have special character or spaces ?
I see that the folder is:

```
 'Visual.nuget\packages\blazormobile.build.android\3.0.11-preview9.19465.2\tools\netcoreapp3.0/'
```

The full path is missing.
Can you confirm that your username folder has a space in it ?

If yes i need to escape input folders correctly in the **GenerateBlazorMobileBuildAndroid.targets** file.

**Comment by Daddoon** [comment]
I think i have found a workaround if the problem is about the path in the MSBuild target.

Please can you confirm me that replacing:

```
C:\Users\YOURUSERNAME\.nuget\packages\blazormobile.build.android\3.0.11-preview9.19465.2\tools\GenerateBlazorMobileBuildAndroid.targets
```

With this content:

```xml
<!-- GenerateBlazorMobileBuildAndroid.targets -->
<Project>

  <!-- Require rebuild if the targets change -->
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>

  <!-- BlazorMobile Iframe Listener WebExtension for GeckoView injected as Asset -->
  
  <PropertyGroup>
    <BlazorMobileBuildAndroidDir Condition="'$(BlazorMobileBuildAndroidDir)' == ''">$(MSBuildThisFileDirectory)netcoreapp3.0/</BlazorMobileBuildAndroidDir>
    <BlazorMobileBuildAndroidFileExe>dotnet &quot;$([MSBuild]::Escape($(BlazorMobileBuildAndroidDir)BlazorMobile.Build.Android.dll))&quot;</BlazorMobileBuildAndroidFileExe>
    <BlazorMobileBuildAndroidInput>&quot;$([MSBuild]::Escape($(MSBuildProjectFullPath)))&quot;</BlazorMobileBuildAndroidInput>
    <!-- The current line below is expected. We do not search about the real obj intermediateOutputPath -->
    <!-- if it's different but just having an ignored directory for version control BUT not prefixed by some Android Debug or SDK version at build -->
    <!-- for injecting somme Android Assets with a consistent path -->
    <BlazorMobileBuildAndroidIntermediateOutputPath>$(MSBuildProjectDirectory)/obj/</BlazorMobileBuildAndroidIntermediateOutputPath>
  </PropertyGroup>

  <Target Name="_InjectBlazorMobileIFrameListenerWebExtension" BeforeTargets="CoreCompile">
    <Exec Command="$(BlazorMobileBuildAndroidFileExe) inject-iframe-listener-webextension --input $(BlazorMobileBuildAndroidInput) --package-dir &quot;$([MSBuild]::Escape($(BlazorMobileBuildAndroidDir)))&quot; --intermediate-output-path &quot;$([MSBuild]::Escape($(BlazorMobileBuildAndroidIntermediateOutputPath)))&quot;" />
  </Target>

  <Target Name="InjectBlazorMobileIFrameListenerWebExtension" DependsOnTargets="_InjectBlazorMobileIFrameListenerWebExtension" BeforeTargets="CoreCompile">
    <ItemGroup>
      <AndroidAsset Include="obj\BlazorMobile\web_extensions\iframe_listener\background.js" />
      <AndroidAsset Include="obj\BlazorMobile\web_extensions\iframe_listener\icons\blazormobile-48.png" />
      <AndroidAsset Include="obj\BlazorMobile\web_extensions\iframe_listener\manifest.json" />
    </ItemGroup>
  </Target>
  
</Project>
```

Does fix your problem after a Clean rebuild of your application ?

If yes, i will address a fix about this.

**Comment by OliverVisual** [comment]
Hi Daddoon,

What is your Visual Studio version ? - Studio Pro 16.3.3
Do you have .NET Core 3.0 installed ? I forgot to write this as a requirement for the additionals CLI tools - yes including most past preview builds.
What is the folder structure of your project on your Filesystem ? There is a space 'Oliver Visual'.

I'm in Australia so apologies if my responses are delayed.

------

I'm not sure about your last comment? which csproj file should I edit?

It's odd because it built and ran in the previous version of your code on the same machine.

The other odd thing I notice is these appear unresolved until I click them - never seen that before.

![image](https://user-images.githubusercontent.com/52524135/66614856-51f5a700-ec16-11e9-8a5c-f29ab43dbb3d.png)

**Comment by Daddoon** [comment]
I released a new version in order to fix your issue.
See [the migration guide](https://github.com/Daddoon/BlazorMobile#blazormobile-3011-preview9194652-to-3012-preview9194652)

**Comment by OliverVisual** [comment]
Awesome thankyou
________________________________

**Comment by Daddoon** [comment]
Just remember to restart Visual Studio after the update, as build tools are not always reloaded after NuGet package update!
