### ISSUE TITLE
Minor: Artifacts folder missing in BlazorMobile.NuGet for NuGet Restore

### ISSUE THREAD

**Issue by ajhena** [Daddoon/BlazorMobile#152]
I added it manually but perhaps add it to the code base.

**Comment by Daddoon** [comment]
Actually, the folder is generated automatically when you compile the solution.
At least, i doesn't prevent me for Building on my machine.

Did you have any issue ?

**Comment by ajhena** [comment]
I kept getting the error that the folder was missing so I went ahead and created it manually. No issues with that now.

**Comment by Daddoon** [comment]
Will add a dummy file to prevent this behavior
