### ISSUE TITLE
How to Implement Platform Specific for ProxyInterface

### ISSUE THREAD

**Issue by endrik-exe** [Daddoon/BlazorMobile#157]
For example, the codes on the android or the Electron.Net is different, so we need to create the implementation separatelly.

How do we achieve that?

From the example i see the implementation is shared between platform, and device identification can be checked with BlazorDevice Class.

is it good?

Thank you.

**Comment by Daddoon** [comment]
You have many way to implement this logic on your project.

And actually the best choice depend of your platform specific requirement.

If it does not need any special platform API, like you said you may use BlazorDevice or Device from the Xamarin project on the "native" end of your project, and do some switches depending the different behavior.

But if you need to access platform specific API, like ElectronNET, Android, iOS etc, the best would be to keep your native ProxyInterface method as is, as i think it's good to keep it common between platforms, but then call a platform specific service in your ProxyInterface code, using Dependencies Injections. There is many implementations now, like the .NET Core style one, or the Xamarin one.

Take a look at [this documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction) and [this documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/registration-and-resolution) for the Xamarin dependency service registration

If you register your service correctly on each platform, if we take the sample ProxyInterface, it would be like something like that:

```csharp
using BlazorMobile.Common;
using BlazorMobile.Sample.Common.Interfaces;
using BlazorMobile.Sample.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace BlazorMobile.Sample.Services
{
    public class XamarinBridge : IXamarinBridge
    {
        public async Task<List<string>> DisplayAlert(string title, string msg, string cancel)
        {
            IMyPlatformSpecificService service = DependencyService.Get<IMyPlatformSpecificService >();
            service.DoSomething();

            return result;
        }
    }
}

```

This way, delegating all non-common code as Platform specific in your interop, to the implemented class inheriting from IMyPlatformSpecificService on each platform.

Of course, you have to define the service on the platform specific project (Desktop (Electron), Android, iOS, UWP....) and register it in the Dependency Services, but this is covered in the documentations i linked to you !

**Comment by endrik-exe** [comment]
Thank you for detailed explanation, and thank you for the great stuff.
