### ISSUE TITLE
[Question] Why the common project folder name is myproject.blazor.common but the project name is myproject.common?

### ISSUE THREAD

**Issue by arivera12** [Daddoon/BlazorMobile#177]
Why the folder is just renamed to myproject.common?

**Comment by Daddoon** [comment]
I think it's just something i forgot in the templates.

Historically i think the projects were called *.Blazor.Common, but as this project is for sharing interfaces between Native and Blazor if needed, i removed the Blazor part on the project file and assembly.

But as you noticed, i may have forgot to rename the folder.

I will keep this issue opened for tracking for a next version.
Thanks !

**Comment by arivera12** [comment]
That's was exactly what I though cause it doesn't make any sense. One more question. Were should I should put my models, resources files (translations)? It should be on this project right? myproject.common?

**Comment by Daddoon** [comment]
Yes it should be this one.

You must consider this project as a clean way to use same kind of data and references between the Xamarin app (Native) and the Blazor one.

So if you need to store data models (Plain C# code, DTO, undecorated / flat SQLite data class model by only using Fluent API in native side), this is the right project.

Anything you are able to link in this project should be reference-able  on both side without tricks.
If you create new interface and Interop services to communicate with native, this is the project where you store the shared interface model.

For ressource yes you can use it, but depend on how you want to use it, it's not mandatory. If you need it on both places (Native and Blazor), yes, but if this is only needed on Blazor, you may store this on the Blazor project (or any Blazor specific project from your solution). Keep in mind that the **.Common** will be generated twice indirectly (one stored in your Blazor package, and the one linked in Xamarin, even if they are the same code at runtime, but not the same environment).

**Comment by arivera12** [comment]
I know this part the code must be as clean as possible. I have faced some libs which doesn't works on blazor wasm and turns to be painful when error message pops out hahaha. I will just put here my models undecorated, fluentvalidations and resource files for translations to share with blazor and web api projects. Thanks again!

**Comment by arivera12** [comment]
@Daddoon Tell me when this change is available I am making a hook with this project with a tool I have developed through this years that does most of the dirty work for most applications that resides on hard crud operations, file management, audit trail, etc. This tool reads a database and expose the api in just minutes and also build the web interface on top of blazor (This parts still needs beautify modifications). Its pretty cool. I have done few projects that are quoted in time for 3 months and I have finish them in just 2 weeks.

**Comment by Daddoon** [comment]
Wich change ? The folder renaming ?

**Comment by arivera12** [comment]
Yes

**Comment by Daddoon** [comment]
I don't understand. Can't you just rename the folder by yourself ? Do you have a requirement to create project from template programmatically ?

**Comment by arivera12** [comment]
exactly I am creating the project from template programmatically.

**Comment by arivera12** [comment]
I can change the output path in the meantime that's no big deal but it would be great that the folder name is the same as the project

**Comment by Daddoon** [comment]
I would prefer to release a new version when i will have updated the BlazorMobile.Build package in order to make it compatible with the last Blazor version format. I will close this issue when fixed.

Sorry i can't estimate a release date yet, i do this project in my freetime.

**Comment by arivera12** [comment]
Don't worry we all do awesome things in our free time. Keep me in the loop when this is added in the next release.

**Comment by Daddoon** [comment]
Done for next version

**Comment by Daddoon** [comment]
The new version is published on Nuget.

- See the [migration guide here](https://github.com/Daddoon/BlazorMobile/blob/master/MIGRATION.md#blazormobile-322-preview1200731-to-323-preview2201605)

**Release notes:**

- Add support of **Blazor 3.2.0-preview2.20160.5**
- Renamed **BlazorMobile.Sample.Blazor.Common** folder to **BlazorMobile.Sample.Common** in templates - project file name is unchanged.
- Updated **BlazorMobile.Build** Nuget package in order to work with the standard publishing model of Blazor integrated in **Blazor 3.2.0-preview2.20160.5**

**Comment by arivera12** [comment]
@Daddoon I will try right now and give feedback!

**Comment by arivera12** [comment]
Worked flawless! Thank you so much @Daddoon!
