### ISSUE TITLE
Anyone has step by step to convert Blazor into mobile without using BlazorMobile

### ISSUE THREAD

**Issue by sorainnosia** [Daddoon/BlazorMobile#198]
I gave up using BlazorMobile

Anyone has step to convert Blazor into WebView and turn to apk in Android?

Thank you

**Comment by Daddoon** [comment]
There is not a lot of alternatives if you are not happy with BlazorMobile, but you have:

- Doing it by yourself: A basic Blazor app is just a WebAssembly app, with regular web files, nothing prevent you to load it manually on your app.
- Trying BlazorWebView of this project: https://github.com/jspuij/BlazorWebView , very young project but seems promising
- Trying BionicCLI: https://github.com/BionicFramework/BionicCLI

The main advantage of BlazorMobile is that the C# interop with the native side is nearly transparent, and you have some cools additional features, like side loading other package or remotely being able to update your app.

The BlazorWebView project will surely have C# interop too.

Too bad you gave up on BlazorMobile. Feedbacks are always appreciated to fix or enhance a product.
