### ISSUE TITLE
After upgrading to BlazorMobile.Templates::3.2.7-preview4.20210.8 Android app starts and closes

### ISSUE THREAD

**Issue by arivera12** [Daddoon/BlazorMobile#209]
I was testing android project on a custom application I am working after upgrading android app runs and closes unexpectedly without showing any error message. 

I though something was wrong on my project so I run a fresh test project from template solution and same behavior happened after trying again.

**Comment by Daddoon** [comment]
Did you update Blazor ?

Current BlazorMobile build has not been tested on last Blazor version.

I will try to take a look when I have the time

**Comment by Daddoon** [comment]
I tested current release with default and last version of Blazor and everything is working as expected.
I will close this issue as this is not reproductible.

In your tests please try force close your app before testing the new version, i had some weird similar issue in the past if the app was previously in memory, somehow.

If the issue still persist, try to redirect your Android logcat content before and after crash, and try to post it here.

Like redirecting it in a file: adb logcat > yourfile.txt

Then launch the app, wait for crash, and when crashed, end the command redirection with CTRL+C in your command prompt.

**Comment by arivera12** [comment]
I tried another android device and everything is working. It's seems something with my android device. I am still investigating how to fix it.

**Comment by Daddoon** [comment]
What is your device Android version ?
CPU type ?

Also as i mentionned, you may have additional info with logcat.
Check if required permissions for your app are present.

**Comment by arivera12** [comment]
> What is your device Android version ?
> CPU type ?
> 
> Also as i mentionned, you may have additional info with logcat.
> Check if required permissions for your app are present.

The device I tested is  exactly the same as mine.

In the past I tried with my device and everything was working but after last week won't work with any android project. 

This seems not to be related with your project I tried a pure android app that I know it was working and the same error ocurred....

**Comment by Daddoon** [comment]
Are your other project using something like Mono Or mono shared runtimes ?

If you build and deploy your app in release mode does the issue still
happen ? This is just for checking that your global error is not a
corrupted shared mono runtime. Release build does not use the shared
runtime as it’s for production.

**Comment by arivera12** [comment]
You hit my problem, my device started working in release mode. How should I fix corrupted shared mono runtime?

**Comment by Daddoon** [comment]
Go to your Android installed apps menu, and uninstall all Mono related app / service / library. It should be something like "Mono shared runtime API 28" or anythings like this.

Then, when you will build your apps using Xamarin (BlazorMobile or not), Visual Studio will detect that the mono runtime is not installed on the device and will try to reinstall it.

If the issue still happen, try to upgrade or downgrade current Android SDK API version OR update or downgrade Xamarin.Forms if you have some doubt. But i'm pretty sure it's just a publishing bug.

**Comment by arivera12** [comment]
I followed your steps and everything is working back as normal! Thank you very much friend! I hope at some point to thank you economically for your time invested on me and this great project. I have a project with great potential using this project under the hood. I will be in touch with you soon, so we can talk about business opportunity together and also you can take advantage of my framework.

**Comment by Daddoon** [comment]
Happy to hear that you have this fixed now !
Curious to see what you will present to me.

Hoping to read you soon.

**Comment by arivera12** [comment]
Its a tool (This will be shared privately with you) on top of a framework (This its public) I have developed since 2014 with high abstraction level. I am finishing a new version of the framework with more abstractions and solid bases and extended classes. It's not ready to use by now cause I have broken it entirely with huge refactors and standards but it should be available and stable in one month as much. Check out the features baked of what is available by now,  [OneLine](https://github.com/arivera12/OneLine)

This is my currently TODO if you wanna keep track.

[Issues](https://github.com/arivera12/OneLine/issues)

**Comment by Daddoon** [comment]
Thanks @arivera12 !

I will be away tomorrow, but i will surely check your project when i come back next week !
Also starred the project.

**Comment by arivera12** [comment]
Let me know when ever you are available and want to have a meeting to explain the basics. I have poor documentation at the moment.
