### ISSUE TITLE
Could not load BlazorMobile.Common

### ISSUE THREAD

**Issue by soend** [Daddoon/BlazorMobile#210]
Hei,
After updating to the latest version of BlazorMobile i cant start the server project anymore. Here is the exception:
`System.IO.FileLoadException: 'Could not load file or assembly 'BlazorMobile.Common, Version=3.2.7.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference.`

I also downloaded the latest BlazorMobile.Sample from repo and its also getting the same exception.

Any ideas what could be causing this?

**Comment by Daddoon** [comment]
Damn, you are the second to tell me this issue but i never had it personally.
Can you try to delete obj and bin folders of your solution ?
Can you try to delete BlazorMobile from your NuGet cache ?

On wich platform are you trying to deploy ?

**Comment by soend** [comment]
Deleting obj, bin and clearing nuget cache did not help.

Current development machine is Windows 10, build 19041.264
Dotnet version 3.1.300

When looking at the BlazorMobile.Common.dll version it shows 1.0.0
[https://i.imgur.com/puHxZcF.png](https://i.imgur.com/puHxZcF.png)

**Comment by Daddoon** [comment]
The version shown does not always reflect the dll version, as i version it mainly from the NuGet package versioning.

Do you have any other BlazorMobile.Common.dll present in Nuget cache from an other BlazorMobile package ? If yes, does replacing the expected one fix the issue ?

Do you have this issue while using BlazorMobile for Mobile or using ElectronNET for Desktop ?
Do you have a minimal repro step to have this bug ?

**Comment by soend** [comment]
> The version shown does not always reflect the dll version, as i version it mainly from the NuGet package versioning.
> 
> Do you have any other BlazorMobile.Common.dll present in Nuget cache from an other BlazorMobile package ? If yes, does replacing the expected one fix the issue ?
> 
> Do you have this issue while using BlazorMobile for Mobile or using ElectronNET for Desktop ?
> Do you have a minimal repro step to have this bug ?

I totally cleared out my nuget cache folder so there cant be any other BlazorMobile.Common.dll's left from other versions. 

I get same exception while using the sample project from BlazorMobile repo.
 When i try to run BlazorMobile.Sample.Blazor.Server project in Visual Studio 2019 Preview (Version 16.7.0 Preview 1.0).
[Here's the full exception trace](https://gist.github.com/soend/6d8cfa2f49dbd2b9bc9b2259eed3b124)

**Comment by Daddoon** [comment]
I will test this on my side. If there is a problem, in my opinion it's something related to Nuget dependencies. I have seen that sometime BlazorMobile.Common is not always generated at first NuGet build task. So i imagine that there is some misleading in the Nuget config maybe.

I will take a look shortly today.

**Comment by Daddoon** [comment]
Ironically i don't have the same error while testing the Server project.

On my side it's:

```
FileNotFoundException: Could not load file or assembly 'BlazorMobile.Common, Version=3.2.7.0, Culture=neutral, PublicKeyToken=null'. Le fichier spécifié est introuvable.
```

BlazorMobile projects are working except the one using the .NET Core stack.
I'm investigating.

**Comment by Daddoon** [comment]
Hi @soend .

First, thanks for your bug report, as this functionnality was working before.

I don't know if this is because of the migration of BlazorMobile.Web package to be packed with **dotnet pack** instead of **nuget pack** but this weird error, only occuring on .NET Core project disappeared on my side when i have migrated BlazorMobile.Common with dotnet pack too.

I don't know if it's related to the tooling directly, or because dotnet pack alter the dll version too when publishing, but it seemed to fix the error for me.

I think i will try to update the way Nuget and dll are generating at build.
But i need some time and some test.

I will come back on this very soon.

**Comment by Daddoon** [comment]
A fix is ready for this issue, at least i don't have error at start anymore on .NET Core / Server project.
I will ship a new version tomorrow, thanks for your patience !

**Comment by Daddoon** [comment]
Hi @soend !

I don't know if you still use BlazorMobile, but a fix has been released for this issue:

https://github.com/Daddoon/BlazorMobile/blob/master/MIGRATION.md#blazormobile-327-preview4202108-to-328

Packages has been published on Nuget.org. If you don't see it, they will surely appear in one hour.
