### ISSUE TITLE
[Question] Mobile app without embedding Blazor app

### ISSUE THREAD

**Issue by vd3d** [Daddoon/BlazorMobile#214]
Hi,

I have a Blazor Web app and wish to have a mobile version.

But, the backend is not accessible outside (not exposed API) and the whole application is composed of:
- a razor app (used for identity)
- a blazer app

Both, have a different URL.

I'm not sure I can use BlazorMobile in such scenario ? right ?

My first idea was to have a Xamarin app with a webview, and simply navigate to the web site url.
Additionally,  I wish to have some "native" controls/widgets and maybe access some native feature.
So I need a bidirectional communication between my webview and the blazor app (by example, when the route change).

So, should I use Blazor mobile or start my own solution ?

Thanks

**Comment by Daddoon** [comment]
It depend of a lot of factor.

First, are you using Blazor Server or Blazor WASM for your Blazor app ?
Only Blazor WASM engine is supported on mobile.

Also, everything depend of the scope of your app, your needs and/or limitations.

**Comment by vd3d** [comment]
Thanks for your anwser,

I use Blazor Server !

**Comment by Daddoon** [comment]
If you use server, there is nothing you can do out of the box, as only the WASM version can be packaged.

Also concerning your idea your Blazor app integration with native call, keep in mind that the Blazor server is executed on...Server ! I mean C# code at least will be executed and managed from a remote location, not directly on your device.

This mean that some usefull data may be not in your client memory directly. You have to keep this in mind while architecturing your project.

So i think it's better that you go on your own route, just keep in mind about security flaw if you open your access through Javascript and/or Websocket too widely in your experimentation.

**Comment by vd3d** [comment]
You're right... thanks for your answer ;-)
