### ISSUE TITLE
Can't Create Bundle

### ISSUE THREAD

**Issue by ghost** [Daddoon/BlazorMobile#233]
The second Issue is we can't create a bundle at API level 29 or API level 30. How to resolve this type of issue

**Comment by Daddoon** [comment]
Actually you can't ship an App Bundle due to the lack of **App Bundle support** on the GeckoView Engine (see here: https://bugzilla.mozilla.org/show_bug.cgi?id=1529082 )

I'm sorry about that, consider deploy multiple APK instead.
