### ISSUE TITLE
How to add Geofencing

### ISSUE THREAD

**Issue by ghost** [Daddoon/BlazorMobile#236]
Hi @Daddoon 

Hope you are doing well.

I try to apply Geofencing functionality on my project in the Blazor. Error comes "Fatal Signal 6".

How we can apply Geofencing functionality on my Blazor project.

**Comment by Daddoon** [comment]
It's related to Android or GeckoView.
Did you add the required permissions for a Geofencing functionnality on your Android project ?

**Comment by ghost** [comment]
Yes 
Every things add on the android project but I am facing the "Fatal Signal 6" error. 
Its take to long time to load application but application stuck on the Splash screen and crash.
